### ISSUE TITLE
Merge fails on "currentVersion"

### ISSUE THREAD

**Issue by jadar** [simonwagner/mergepbx#18]
I have a project which had a new data model created on both branches. When we try to merge using the tool, it fails on the XCVersionGroupMerger3. Specifically the isa, "XCVersionGroup," with "currentVersion" and "children" conflicting.
![mytraps_fixreleaes_ _vim_mytraps_xcodeproj_project_pbxproj_ _vim_mytraps_xcodeproj_project_pbxproj_ _solarized_dark_ansi_ _259x60](https://cloud.githubusercontent.com/assets/3793928/11676724/0785391e-9dfb-11e5-8707-44584df751e6.png)
![screen_shot_2015-12-08_at_10_28_51_pm](https://cloud.githubusercontent.com/assets/3793928/11676751/6f56184c-9dfb-11e5-9927-7064a541ce01.png)

**Comment by simonwagner** [comment]
Hm, well that is kinda a "real" merge conflict. mergepbx sees that the `currentVersion` has diverged in both branches and so they conflict on `currentVersion`. (Because what should it be? `16A9`... or `E9BD...`)

mergepbx could solve it by noticing that there are two entries for files with different IDs but the same path and then just remove the superfluous file entry and replace its ID with the ID of the remaining entry. I am unsure whether that will be save enough to implement as a default behaviour.

Hm, so I would say, mergepbx is doing what it should - but lets see maybe I will add a `--dangerously-merge-duplicate-file-entries`. But for now it's working as intended.
